name: Build GeoSite

on:
  workflow_dispatch:
  push:
    paths:
      - 'geosite-rules/**.txt'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout your repository
        uses: actions/checkout@v4
        with:
          path: my-rules

      - name: Checkout domain-list-community compiler
        uses: actions/checkout@v4
        with:
          repository: v2fly/domain-list-community
          path: compiler

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build geosite.dat
        run: |
          # Переименовываем все .txt файлы в нижний регистр перед копированием
          mkdir -p temp_rules
          for f in my-rules/geosite-rules/*.txt; do
            base=$(basename "$f" .txt)
            lower=$(echo "$base" | tr '[:upper:]' '[:lower:]')
            cp "$f" "temp_rules/${lower}.txt"
          done
          cp temp_rules/*.txt compiler/data/

          cd compiler
          go run ./ --outputdir=../ --outputname=geosite.dat

      - name: Create Release and Upload Asset
        uses: softprops/action-gh-release@v2
        with:
          tag_name: geosite-latest
          files: geosite.dat
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
