name: Build GeoIP

on:
  push:
    paths:
      - 'geoip-rules/**.txt'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download geoip binary
        run: |
          wget https://github.com/v2fly/geoip/releases/download/20240411163810/geoip-linux-64
          chmod +x geoip-linux-64
          mv geoip-linux-64 geoip

      - name: Prepare custom IP list
        run: |
          cat geoip-rules/*.txt > custom-ips.txt
          echo "text:custom-ips.txt" > config.json

      - name: Build geoip.dat
        run: |
          ./geoip -c config.json -o geoip.dat

      - name: Create Release and Upload Asset
        uses: softprops/action-gh-release@v2
        with:
          tag_name: geoip-latest
          name: GeoIP Latest
          body: Автоматическая сборка geoip.dat
          draft: false
          prerelease: false
          files: geoip.dat
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
